site_name: SSF Cookiecutter Data Science Template
site_description: A project template and directory structure for Python data science projects.
site_favicon: favicon.ico
repo_url: https://github.com/sausolofer/SSF_Personal_Data_Science_Template
edit_uri: edit/master/docs/docs
theme: cinder
extra_css:
  - css/extra.css
nav:
  - Home: index.md
